# Assignment-2 Chandra Shekhar

# Random

In [1]:
import numpy as np

# Rand

In [4]:
np.random.rand(5)

array([0.33237402, 0.86165155, 0.21021983, 0.96735953, 0.66878937])

In [5]:
np.random.randint(20)

7

In [6]:
np.random.rand(3,3)

array([[0.64079395, 0.92807297, 0.34967638],
       [0.53460124, 0.13660433, 0.50552485],
       [0.88400159, 0.0582777 , 0.4496776 ]])

# Randn

In [10]:
np.random.randn(5,5)

array([[-0.10809505,  0.98811822,  0.49359601,  0.23583273,  0.63143576],
       [ 0.89945034,  0.25499422, -0.14077663,  1.78083991,  1.07297161],
       [-0.28928299, -0.25123344, -0.29494932,  0.2697487 , -0.48759951],
       [-0.09651408, -1.87002517,  0.10835493,  0.96211085,  1.00769895],
       [-0.44175413, -0.87024215,  0.49005612, -0.28676931,  1.48769841]])

In [12]:
np.random.randn(5,5)+5

array([[5.13451537, 4.70161712, 4.99716118, 6.21505344, 5.83086583],
       [7.07626058, 6.52414513, 4.96270166, 5.60649469, 4.23353715],
       [3.01303196, 5.70466017, 4.7063344 , 4.23044764, 4.48282782],
       [5.5700024 , 4.09421557, 4.47212017, 6.43270394, 4.70368278],
       [6.74784843, 4.6218313 , 6.88644265, 4.08368678, 5.69930004]])

# Randint

In [17]:
np.random.randint(5)

1

In [19]:
np.random.randint(10,80)

29

# Array Attributes and Methods

# Reshape

In [21]:
arr=np.arange(15)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Shape

In [26]:
arr.shape

(15,)

In [27]:
ar=arr.reshape(3,5)

In [28]:
ar.shape

(3, 5)

# Dtype

In [30]:
arr.dtype

dtype('int32')

# Indexing and Selection

In [31]:
arr1=np.arange(10,20)

In [32]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
arr1[5]

15

In [34]:
arr1[-1]

19

In [37]:
arr1[7]

17

In [39]:
arr1[:8]

array([10, 11, 12, 13, 14, 15, 16, 17])

In [40]:
arr1[4:9]

array([14, 15, 16, 17, 18])

# Broadcasting

In [41]:
x=np.array([2,6,4,8,0])
y=np.array([1,3,5,9,7])

In [42]:
z=x*y

In [43]:
z

array([ 2, 18, 20, 72,  0])

In [44]:
x+5

array([ 7, 11,  9, 13,  5])

In [46]:
c=np.array([[1,2,3,4],[5,6,7,8]])
k=7
y=c+k
y

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Indexing 2D Array/Matrix

In [48]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr_2d.shape

(3, 3)

In [52]:
arr_2d.ndim

2

In [54]:
arr_2d[1]

array([4, 5, 6])

In [58]:
arr_2d[:,1]

array([2, 5, 8])

# Fancy Indexing 

In [59]:
arr=np.zeros((3,3))

In [60]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
len=arr.shape[0]
len

3

In [64]:
for i in range(len):
    arr[i]=i
    print(arr[i])

[0. 0. 0.]
[1. 1. 1.]
[2. 2. 2.]


# Selection

In [66]:
arr=np.arange(0,10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [69]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Universal Array Functions

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
np.max(arr)

9

In [74]:
np.min(arr)

0

In [76]:
np.log(arr)

C:\Users\shekh\AppData\Local\Temp/ipykernel_10612/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
np.mean(arr)

4.5

# Append, Concatenate and Stack

In [78]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr.shape

(10,)

In [81]:
arr_2d=np.array([[1,2,3],[4,5,6]])

In [82]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
arr1=np.array([6,9,8])

# Concatenate

In [93]:
np.concatenate((arr,arr1),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 9, 8])

In [97]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr1=np.array([[7,8,9]])

In [99]:
arr1

array([[7, 8, 9]])

In [101]:
np.concatenate((arr,arr1),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Stack

In [104]:
np.vstack((arr,arr1))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])